/**
 * @file
 */
/** Declaration file generated by dts-gen */
declare module 'san-update' {
    export function apply(r: any, n: any, e: any): any;
    export function applyWith(r: any, n: any, e: any, t: any): any;
    export function builder(): any;
    export function chain(r: any): any;
    export function composeAfter(r: any, n: any, e: any): any;
    export function composeBefore(r: any, n: any, e: any): any;
    export function defaults(r: any, n: any, e: any): any;
    export function filter(r: any, n: any, e: any): any;
    export function immutable(r: any): any;
    export function macro(): any;
    export function map(r: any, n: any, e: any): any;
    export function merge(r: any, n: any, e: any): any;
    export function omit(r: any, n: any, ...args: any[]): any;
    export function pop(r: any, n: any, e: any): any;
    export function push(r: any, n: any, e: any): any;
    export function reduce(r: any, n: any, ...args: any[]): any;
    export function remove(r: any, n: any, e: any): any;
    export function removeAt(r: any, n: any, e: any): any;
    export function set(r: any, n: any, e: any): any;
    export function shift(r: any, n: any, e: any): any;
    export function splice(r: any, n: any, e: any, t: any, ...args: any[]): any;
    export function unshift(r: any, n: any, e: any): any;
    export function update(r: any, n: any): any;
    export function updateBuilder(): any;
    export function withDiff(n: any, o: any): any;
}
